villas2/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from . import settings as base
from apps.main import views
from apps.utils import errors

urlpatterns = [
    url(r'^$', views.log_in, name='entrar'),
    url(r'^salir/', views.salir, name='salir'),
    url(r'^admin/', admin.site.urls),
    url(r'^chaining/', include('smart_selects.urls')),
    # apps
    url(r'^empleabilidad/', include('apps.empleabilidad.urls', namespace='empleabilidad')),
    url(r'^emprendimiento/', include('apps.emprendimiento.urls', namespace='emprendimiento')),
    url(r'^habilidades_blandas/', include('apps.habilidades_blandas.urls', namespace='habilidades_blandas')),
    url(r'^main/', include('apps.main.urls', namespace='main')),
    url(r'^personas/', include('apps.personas.urls', namespace='personas')),

] + static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)

handler400 = errors.error400
handler403 = errors.error403
handler404 = errors.error404
handler500 = errors.error500

apps/empleabilidad/forms.py
from django import forms
from . import models
from apps.utils import forms as utils, constants
from django.forms import models as models_form
from apps.personas import models as persona_models


class VacanteForm(utils.BaseFormAllFields):
    title = 'Vacante'
    fecha = forms.DateField(input_formats=constants.INPUT_FORMATS)

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.Vacante

    def clean(self):
        print(self.cleaned_data)
        return self.cleaned_data


class VacantePersonaForm(utils.BaseFormAllFields):
    title = 'Vacante Persona'

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.VacantePersona


def get_vacante_persona_formset(form,
                                formset=models_form.BaseInlineFormSet,
                                **kwargs):
    return models_form.inlineformset_factory(
        persona_models.Persona,
        models.VacantePersona,
        form,
        formset,
        **kwargs
    )


class FormacionTrabajoForm(utils.BaseFormAllFields):
    title = 'Formacion para el trabajo'
    fecha_creacion = forms.DateField(input_formats=constants.INPUT_FORMATS)

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.FormacionTrabajo


class FormacionTrabajoPersonasForm(utils.BaseFormAllFields):
    title = 'Formacion Trabajo Persona'
    fecha_inscripcion = forms.DateField(input_formats=constants.INPUT_FORMATS)
    fecha_proceso = forms.DateField(input_formats=constants.INPUT_FORMATS)

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.FormacionTrabajoPersona


def get_formacion_trabajo_persona_formset(form,
                                          formset=models_form.BaseInlineFormSet,
                                          **kwargs):
    return models_form.inlineformset_factory(
        persona_models.Persona,
        models.FormacionTrabajoPersona,
        form,
        formset,
        **kwargs
    )

apps/personas/forms.py
from django import forms
from django.forms import models as models_form
from easy_select2 import Select2

from . import models
from apps.utils import forms as utils, constants


class GradoEscolaridadForm(utils.BaseFormAllFields):
    title = 'Grado de escolaridad'

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.GradoEscolaridad


class TituloGradoForm(utils.BaseFormAllFields):
    title = 'Titulo de grado'

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.TituloGrado


class TipoViviendaForm(utils.BaseFormAllFields):
    title = 'Tipo de vivienda'

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.TipoVivienda


class TipoManzanaForm(utils.BaseFormAllFields):
    title = 'Tipo de manzana'

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.TipoManzana


class ManzanaForm(utils.BaseFormAllFields):
    title = 'Manzana'

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.Manzana


class CasaForm(utils.BaseFormAllFields):
    title = 'Casa'
    numero_manzana = forms.ModelChoiceField(
        queryset=models.Manzana.objects.all(),
        widget=Select2()
    )

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.Casa


class PersonaForm(utils.BaseFormAllFields):
    title = 'Persona'
    fecha_ingreso = forms.DateField(input_formats=constants.INPUT_FORMATS)
    widget = forms.FileInput
    hoja_de_vida = forms.FileField(widget=widget)

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.Persona


class ExperienciaLaboralForm(utils.BaseFormAllFields):
    title = 'Experiencia Laboral'

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.ExperienciaLaboralPersona


def get_experiencia_laboral_persona_formset(form,
                                            formset=models_form.BaseInlineFormSet,
                                            **kwargs):
    return models_form.inlineformset_factory(
        models.Persona,
        models.ExperienciaLaboralPersona,
        form,
        formset,
        **kwargs
    )


class TipoFormacionComplementariaForm(utils.BaseFormAllFields):
    title = 'Tipo de formacion'

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.TipoFormacionComplementaria


class FormacionComplementariaForm(utils.BaseFormAllFields):
    title = 'Formacion Complementaria'

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.FormacionComplementariaPersona


def get_formacion_complementaria_persona_formset(form,
                                            formset=models_form.BaseInlineFormSet,
                                            **kwargs):
    return models_form.inlineformset_factory(
        models.Persona,
        models.FormacionComplementariaPersona,
        form,
        formset,
        **kwargs
    )

templates/apps/base/base_form.html
{% extends 'index.html' %}
{% block main %}
    <br>
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default" data-widget="{&quot;draggable&quot;: &quot;false&quot;}"
                 data-widget-static=""
                 style="visibility: visible; opacity: 1; display: block; transform: translateY(0px);">
                <div class="panel-heading">
                    <h2>
                        {{ action }} {{ form.title }}
                    </h2>
                    {% if form.errors %}
                        <br>
                        <div class="alert alert-danger alert-dismissable text-center">
                            <button type="button" class="close" data-dismiss="alert"
                                    aria-hidden="true"></button>
                            <strong>Error!</strong>
                            {% if not form.non_field_errors %}
                                por favor revise los campos marcados
                            {% else %}
                                {% for error in form.non_field_errors %}
                                    {{ error|escape }}
                                {% endfor %}
                            {% endif %}
                        </div>

                    {% endif %}
                    <div class="panel-ctrls" data-actions-container=""
                         data-action-collapse="{&quot;target&quot;: &quot;.panel-body, .panel-footer&quot;}"><span
                            class="button-icon has-bg"><span class="material-icons">keyboard_arrow_up</span></span>
                    </div>
                </div>
                {% include 'apps/base/form.html' %}
            </div>
        </div>
    </div>
{% endblock %}

{% block js_extra %}
    <script>
        $(document).ready(function () {

            $('#id_fecha, #id_fecha_creacion, #id_fecha_ingreso, .date-picker').datepicker({
                todayHighlight: true,
                dateFormat: 'mm/dd/yyyy'
            });

        });
    </script>

{% endblock %}

templates/apps/base/form.html
{% load widget_tweaks %}
<form method="post" class="form-horizontal">{% csrf_token %}
    <div class="panel-body">
        {% for field in form %}
            <div class="form-group is-empty {% if field.errors %}has-error{% elif field.value %}has-success{% endif %}">
                <label class="col-md-2 control-label">{{ field.label }}</label>
                <div class="col-md-8">
                    <div class="input-group">
                        <span class="input-group-addon"></span>
                        {% render_field field class="form-control" placeholder=field.label %}
                        <strong class="text-danger">
                            {{ field.errors }}
                        </strong>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="panel-footer">
        <div class="row">
            <div class="col-sm-4 col-sm-offset-5">
                <button class="btn-raised btn-success btn">
                    {{ action }}
                </button>
            </div>
        </div>
    </div>
</form>

templates/apps/base/list_base.html
{% extends 'index.html' %}

{% load i18n staticfiles %}

{% block css_extra %}
    <link href="{% static 'assets/plugins/datatables/dataTables.bootstrap.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'assets/plugins/datatables/dataTables.themify.css' %}" type="text/css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'datatables/css/buttons.bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'datatables/css/colReorder.bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'datatables/css/fixedColumns.bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'datatables/css/fixedHeader.bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'datatables/css/keyTable.bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'datatables/css/responsive.bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'datatables/css/rowGroup.bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'datatables/css/rowReorder.bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'datatables/css/scroller.bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'datatables/css/select.bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'easy_select2/vendor/select2/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'easy_select2/css/easy_select2.css' %}">
{% endblock %}

{% block js_extra %}
    <script src="{% static 'assets/plugins/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'assets/plugins/datatables/dataTables.bootstrap.js' %}"></script>
    <script src="{% static 'assets/demo/demo-datatables.js'%}"></script>
    <script src="{% static 'datatables/js/dataTables.buttons.min.js'%}"></script>
    <script src="{% static 'datatables/js/buttons.bootstrap.min.js'%}"></script>
    <script src="{% static 'datatables/js/buttons.colVis.min.js'%}"></script>
    <script src="{% static 'datatables/js/buttons.flash.min.js'%}"></script>
    <script src="{% static 'datatables/js/buttons.html5.min.js'%}"></script>
    <script src="{% static 'datatables/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'datatables/js/dataTables.colReorder.min.js'%}"></script>
    <script src="{% static 'datatables/js/dataTables.fixedColumns.min.js'%}"></script>
    <script src="{% static 'datatables/js/dataTables.fixedHeader.min.js'%}"></script>
    <script src="{% static 'datatables/js/dataTables.keyTable.min.js'%}"></script>
    <script src="{% static 'datatables/js/dataTables.responsive.min.js'%}"></script>
    <script src="{% static 'datatables/js/responsive.bootstrap.min.js'%}"></script>
    <script src="{% static 'datatables/js/dataTables.rowGroup.min.js'%}"></script>
    <script src="{% static 'datatables/js/dataTables.rowReorder.min.js'%}"></script>
    <script src="{% static 'datatables/js/dataTables.scroller.min.js' %}"></script>
    <script src="{% static 'datatables/js/dataTables.select.min.js' %}"></script>
    <script src="{% static 'easy_select2/js/init.js' %}" type="text/javascript"></script>
    <script src="{% static 'easy_select2/js/easy_select2.js' %}"></script>
    <script src="{% static 'easy_select2/js/lookup_override.1.8.js' %}"></script>
    <script src="{% static 'js/select2.min.js' %}"></script>
    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
            $('[data-tooltip="true"]').tooltip();
            $('.panel-ctrls-center > input').attr('placeholder', 'Buscar...');
            $('.dt-button').addClass('btn');
            $('.buttons-excel').addClass('btn-success btn-raised').removeClass('dt-button');
            $('.buttons-copy').addClass('btn-info btn-raised').removeClass('dt-button');
            $('.buttons-pdf').addClass('btn-danger btn-raised').removeClass('dt-button');
            $('.buttons-colvis').addClass('btn-inverse btn-raised').removeClass('dt-button');
            $('.buttons-print').addClass('btn-primary btn-raised').removeClass('dt-button');
        });
    </script>
{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2>{% block title_table %}{% endblock %}</h2>
                    <div class="panel-ctrls"></div>
                </div>
                <div class="panel-body no-padding">
                    <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
                        <thead>
                        <tr>
                            {% block content_main_header_table %}
                            {% for item in header_table %}
                                <th class="text-center">{{ item }}</th>
                            {% endfor %}
                        {% endblock %}
                        </tr>
                        </thead>
                        <tbody>
                            {% if list %}
                                {% for obj in list %}
                                    {% block content_main_table_data %}
                                    {% endblock %}
                                {% endfor %}
                            {% endif %}
                        </tbody>
                    </table>
                </div>
                <div class="panel-footer"></div>
            </div>
        </div>
    </div>
{% endblock %}