apps/empleabilidad/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    # vacantes

    url(r'^crear-vacante/',
        views.VacanteCreateView.as_view(),
        name='crear_vacante'),

    url(r'^editar-vacante/(?P<pk>\d+)/',
        views.VacanteUpdateView.as_view(),
        name='editar_vacante'),

    url(r'^lista-vacantes/',
        views.VacanteListView.as_view(),
        name='lista_vacantes'),

    # formacion para el trabajo

    url(r'^crear-formacion-trabajo/',
        views.FormacionTrabajoCreateView.as_view(),
        name='crear_formacion_trabajo'),

    url(r'^editar-formacion-trabajo/(?P<pk>\d+)/',
        views.FormacionTrabajoUpdateView.as_view(),
        name='editar_formacion_trabajo'),

    url(r'^lista-formaciones-trabajo/',
        views.FormacionTrabajoListView.as_view(),
        name='lista_formaciones_trabajo')


]

apps/emprendimiento/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    url(r'^crear-tipo-negocio/',
        views.TipoNegocioCreateView.as_view(),
        name='crear_tipo_negocio'),

    url(r'^editar-tipo-negocio/(?P<pk>\d+)/',
        views.TipoNegocioUpdateView.as_view(),
        name='editar_tipo_negocio'),

    url(r'^lista-tipo-negocio/',
        views.TipoNegocioListView.as_view(),
        name='lista_tipo_negocio'),

    url(r'^crear-tipo-unidad-productiva/',
        views.TipoUnidadProductivaCreateView.as_view(),
        name='crear_tipo_unidad_productiva'),

    url(r'^editar-tipo-unidad-productiva/(?P<pk>\d+)',
        views.TipoUnidadProductivaUpdateView.as_view(),
        name='editar_tipo_unidad_productiva'),

    url(r'^lista-tipo-unidad-productiva/',
        views.TipoUnidadProductivaListView.as_view(),
        name='lista_tipo_unidad_productiva'),

    url(r'^crear-sector/',
        views.SectorCreateView.as_view(),
        name='crear_sector'),

    url(r'^editar-sector/(?P<pk>\d+)/',
        views.SectorUpdateView.as_view(),
        name='editar_sector'),

    url(r'^lista-sectores/',
        views.SectorListView.as_view(),
        name='lista_sectores'),

    url(r'^crear-negocios/',
        views.NegocioCreateView.as_view(),
        name='crear_negocio'),

    url(r'^editar-negocio/(?P<pk>\d+)',
        views.NegocioUpdateView.as_view(),
        name='editar_negocio'),

    url(r'^lista-negocio/',
        views.NegocioListView.as_view(),
        name='lista_negocio'),

    url(r'^crear-empresa/',
        views.EmpresaCreateView.as_view(),
        name='crear_empresa'),

    url(r'^editar-empresa/(?P<pk>\d+)',
        views.EmpresaUpdateView.as_view(),
        name='editar_empresa'),

    url(r'^lista-empresa/',
        views.EmpresaListView.as_view(),
        name='lista_empresa'),

    url(r'^crear-emprendimiento/',
        views.EmprendimientoCreateView.as_view(),
        name='crear_emprendimiento'),

    url(r'^editar-empresa/(?P<pk>\d+)',
        views.EmpresaUpdateView.as_view(),
        name='editar_empresa'),

    url(r'^lista-emprendimiento/',
        views.EmprendimientoListView.as_view(),
        name='lista_emprendimiento'),

    url(r'^crear-oportunidad-comercial/',
        views.OportunidadComercialCreateView.as_view(),
        name='crear_oportunidad_comercial'),

    url(r'^editar-oportunidad-comercial/(?P<pk>\d+)',
        views.OportuniadadComercialUpdateView.as_view(),
        name='editar_emprendimiento'),

    url(r'^lista-oportunidad-comercial/',
        views.OportunidadComercialListView.as_view(),
        name='lista_oportunidad_comercial'),

    url(r'^crear-fortalecimiento-empresarial/',
        views.FortalecimientoEmpresarialCreateView.as_view(),
        name='crear_fortalecimiento_empresarial'),

    url(r'^editar_fortalecimiento_empresarial/(?P<pk>\d+)',
        views.FortalecimientoEmpresarialUpdateView.as_view(),
        name='editar_fortalecimiento_empresarial'),

    url(r'^lista-fortalecimiento-empresarial/',
        views.FortalecimientoEmpresarialListView.as_view(),
        name='lista_fortalecimiento_empresarial'),
]

apps/main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^inicio/',
        views.InicioTemplateView.as_view(),
        name='inicio'),

]

apps/personas/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

   # tipos de formacion complementaria

    url(r'^crear-tipo-formacion-complementaria/',
        views.TipoFormacionComplementariaCreateView.as_view(),
        name='crear_tipo_formacion_complementaria'),

    url(r'^editar-tipo-formacion-complementaria/(?P<pk>\d+)/',
        views.TipoFormacionComplementariaUpdateView.as_view(),
        name='editar_tipo_formacion_complementaria'),

    url(r'^lista-tipos-formacion-complementaria/',
        views.TipoFormacionComplementariaListView.as_view(),
        name='lista_tipos_formacion_complementaria'),

    # grados de escolaridad

    url(r'^crear-grado-escolaridad/',
        views.GradoEscolaridadCreateView.as_view(),
        name='crear_grado_escolaridad'),

    url(r'^editar-grado-escolaridad/(?P<pk>\d+)/',
        views.GradoEscolaridadUpdateView.as_view(),
        name='editar_grado_escolaridad'
        ),

    url(r'^lista-grados-escolaridad/',
        views.GradoEscolaridadListView.as_view(),
        name='lista_grados_escolaridad'),

    # titulos de grado

    url(r'^crear-titulo-grado/',
        views.TituloGradoCreateView.as_view(),
        name='crear_titulo_grado'),

    url(r'^editar-titulo-grado/(?P<pk>\d+)/',
        views.TituloGradoUpdateView.as_view(),
        name='editar_titulo_grado'),

    url(r'^lista-titulos-grado/',
        views.TituloGradoListView.as_view(),
        name='lista_titulos_grado'),

    # tipos de manzana

    url(r'^crear-tipo-manzana/',
        views.TipoManzanaCreateView.as_view(),
        name='crear_tipo_manzana'),

    url(r'^editar-tipo-manzana/(?P<pk>\d+)/',
        views.TipoManzanaUpdateView.as_view(),
        name='editar_tipo_manzana'),

    url(r'^lista-tipos-manzana/',
        views.TipoManzanaListView.as_view(),
        name='lista_tipos_manzana'),

    # tipos de vivienda

    url(r'^crear-tipo-vivienda/',
        views.TipoViviendaCreateView.as_view(),
        name='crear_tipo_vivienda'),

    url(r'^editar-tipo-vivienda/(?P<pk>\d+)/',
        views.TipoViviendaUpdateView.as_view(),
        name='editar_tipo_vivienda'),

    url(r'^lista-tipos-vivienda/',
        views.TipoViviendaListView.as_view(),
        name='lista_tipos_vivienda'),

    # manzanas

    url(r'^crear-manzana/',
        views.ManzanaCreateView.as_view(),
        name='crear_manzana'),

    url(r'^editar-manzana/(?P<pk>\d+)/',
        views.ManzanaUpdateView.as_view(),
        name='editar_manzana'),

    url(r'^lista-manzanas/',
        views.ManzanaListView.as_view(),
        name='lista_manzanas'),

    # casas

    url(r'^crear-casa/',
        views.CasaCreateView.as_view(),
        name='crear_casa'),

    url(r'^editar-casa/(?P<pk>\d+)/',
            views.CasaUpdateView.as_view(),
        name='editar_casa'),

    url(r'^lista-casas/',
        views.CasaListView.as_view(),
        name='lista_casas'),

    # personas

    url(r'^crear-persona/',
        views.crear_persona,
        name='crear_persona'),

    url(r'^editar-persona/(?P<pk>\d+)/',
        views.editar_persona,
        name='editar_persona'),

    url(r'^lista-personas/',
        views.PersonasListView.as_view(),
        name='lista_personas'),

    url(r'^detalle-persona/(?P<pk>\d+)/',
        views.PersonaDetailView.as_view(),
        name='detalle_persona'),


]

villas2/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from . import settings as base
from apps.main import views
from apps.utils import errors

urlpatterns = [
    url(r'^$', views.log_in, name='entrar'),
    url(r'^salir/', views.salir, name='salir'),
    url(r'^admin/', admin.site.urls),
    url(r'^chaining/', include('smart_selects.urls')),
    # apps
    url(r'^empleabilidad/', include('apps.empleabilidad.urls', namespace='empleabilidad')),
    url(r'^emprendimiento/', include('apps.emprendimiento.urls', namespace='emprendimiento')),
    url(r'^habilidades_blandas/', include('apps.habilidades_blandas.urls', namespace='habilidades_blandas')),
    url(r'^main/', include('apps.main.urls', namespace='main')),
    url(r'^personas/', include('apps.personas.urls', namespace='personas')),

] + static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)

handler400 = errors.error400
handler403 = errors.error403
handler404 = errors.error404
handler500 = errors.error500

templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <title>Villas de San Pablo</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="description" content="Paper - Material Admin Theme">
    <meta name="author" content="KaijuThemes">
    <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
        <script>
            // Use same django for material and django admin
            var django = django || {};
            django.jQuery = jQuery.noConflict(true);
            window.jQuery = window.$ = django.jQuery
        </script>
    <script type="text/javascript" src="{% static 'admin/js/jquery.init.js' %}"></script>
    <link type='text/css' href='http://fonts.googleapis.com/css?family=Roboto:300,400,400italic,500' rel='stylesheet'>
    <link type='text/css' href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="{% static 'assets/css/styles.css' %}" type="text/css" rel="stylesheet">
    <!-- Core CSS with all styles -->

    <link href="{% static 'assets/plugins/codeprettifier/prettify.css' %}" type="text/css" rel="stylesheet">
    <!-- Code Prettifier -->

    <link href="{% static 'assets/plugins/dropdown.js/jquery.dropdown.css' %}" type="text/css" rel="stylesheet">
    <!-- iCheck -->
    <link href="{% static 'assets/plugins/progress-skylo/skylo.css' %}" type="text/css" rel="stylesheet">
    <!-- Skylo -->


    <link href="{% static 'assets/plugins/form-daterangepicker/daterangepicker-bs3.css' %}" type="text/css"
          rel="stylesheet">
    <!-- DateRangePicker -->
    <link href="{% static 'assets/plugins/fullcalendar/fullcalendar.css' %}" type="text/css" rel="stylesheet">

   {% block css_extra %}{% endblock %}

</head>

<body class="animated-content infobar-overlay">


<header id="topnav" class="navbar navbar-default navbar-fixed-top  navbar-indigo" role="banner">
    <!-- <div id="page-progress-loader" class="show"></div> -->

    <div class="logo-area">
        <a class="navbar-brand navbar-brand-primary" href="index.html">
            <img class="show-on-collapse img-logo-white" alt="Paper"
                 src="{% static 'assets/img/logo-icon-white.png' %}">
            <img class="show-on-collapse img-logo-dark" alt="Paper" src="{% static 'assets/img/logo-icon-dark.png' %}">
        </a>

        <span id="trigger-sidebar" class="toolbar-trigger toolbar-icon-bg stay-on-search">
                 <a data-toggle="tooltips" data-placement="right" title="Toggle Sidebar">
                    <span class="icon-bg">
                       <i class="material-icons">menu</i>
                   </span>
               </a>
           </span>
    </div><!-- logo-area -->

    <ul class="nav navbar-nav toolbar pull-right">

        <li class="toolbar-icon-bg appear-on-search ov-h" id="trigger-search-close">
            <a class="toggle-fullscreen">
                <span class="icon-bg">
                  <i class="material-icons">close</i>
              </span>
            </a>
        </li>
        <li class="toolbar-icon-bg hidden-xs" id="trigger-fullscreen">
            <a href="#" class="toggle-fullscreen">
            <span class="icon-bg">
              <i class="material-icons">fullscreen</i>
          </span>
            </a>
        </li>

        <li class="dropdown toolbar-icon-bg">
            <a href="#" class="hasnotifications dropdown-toggle" data-toggle='dropdown'><span class="icon-bg"><i
                    class="material-icons">account_circle</i></span><span class="badge badge-info"></span></a>
            <div class="dropdown-menu animated notifications">
                <div class="topnav-dropdown-header">
                    <span>Acciones de usuario</span>
                </div>

                <div class="topnav-dropdown-footer">
                    <a href="{% url 'admin:index' %}" target="_blank">
                        Ir al administrador
                    </a>
                </div>
                <div class="topnav-dropdown-footer">
                    <a href="{% url 'salir' %}" class="text-danger">Cerrar Sesion</a>
                </div>
            </div>
        </li>


    </ul>

</header>

<div id="wrapper">
    <div id="layout-static">
        <div class="static-sidebar-wrapper sidebar-indigo">
            <div class="static-sidebar">
                <div class="sidebar">
                    <div class="widget" id="widget-profileinfo">
                        <div class="widget-body">
                            <div class="userinfo ">
                                <div class="avatar pull-left">

                                </div>
                                <div class="info">
                                    <span class="username">
                                        {{ user.get_full_name }}
                                    </span>
                                    <span class="useremail">{{ user.email }}</span>
                                </div>

                                <div class="acct-dropdown clearfix dropdown">
                                    <span class="pull-left"><span class="online-status online"></span>Online</span>
                                    <!-- <span class="pull-right dropdown-toggle" data-toggle="dropdown"><a href="javascript:void(0)" class="btn btn-fab-caret btn-xs btn-fab"><i class="material-icons">arrow_drop_down</i><div class="ripple-container"></div></a></span>
                                    <ul class="dropdown-menu">
                                        <li><span class="online-status online"></span> Online</li>
                                        <li><span class="online-status online"></span> Online</li>
                                        <li><span class="online-status online"></span> Online</li>
                                        <li><span class="online-status online"></span> Online</li>
                                    </ul> -->
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="widget stay-on-collapse" id="widget-sidebar">
                        <nav role="navigation" class="widget-body">
                            {% include 'sidebar_menu.html' %}
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <div class="static-content-wrapper">
            <div class="static-content">
                <div class="page-content">
                    <div class="container-fluid">
                        <div data-widget-group="group1" style="margin-top: 5%;">
                            {% block main %}
                            {% endblock %}
                        </div>
                    </div> <!-- .container-fluid -->
                </div> <!-- #page-content -->
            </div>
            <footer role="contentinfo">
                <div class="clearfix">
                    <ul class="list-unstyled list-inline pull-left">
                        <li><h6 style="margin: 0;">&copy; 2017 Villas de San Pablo</h6></li>
                    </ul>
                </div>
            </footer>

        </div>
    </div>
</div>


<!-- Das FAB -->
{% block fab %}
{% endblock %}

<!-- Switcher -->
<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
<!-- Load jQuery -->
<script src="{% static 'assets/js/jqueryui-1.10.3.min.js' %}"></script>
<!-- Load jQueryUI -->
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>                                <!-- Load Bootstrap -->
<script src="{% static 'assets/js/enquire.min.js' %}"></script>                                    <!-- Load Enquire -->

<script src="{% static 'assets/plugins/velocityjs/velocity.min.js' %}"></script>
<!-- Load Velocity for Animated Content -->
<script src="{% static 'assets/plugins/velocityjs/velocity.ui.min.js' %}"></script>

<script src="{% static 'assets/plugins/progress-skylo/skylo.js' %}"></script>        <!-- Skylo -->

<script src="{% static 'assets/plugins/wijets/wijets.js' %}"></script>                            <!-- Wijet -->

<script src="{% static 'assets/plugins/sparklines/jquery.sparklines.min.js' %}"></script>             <!-- Sparkline -->

<script src="{% static 'assets/plugins/codeprettifier/prettify.js' %}"></script>
<!-- Code Prettifier  -->

<script src="{% static 'assets/plugins/bootstrap-tabdrop/js/bootstrap-tabdrop.js' %}"></script>
<!-- Bootstrap Tabdrop -->

<script src="{% static 'assets/plugins/nanoScroller/js/jquery.nanoscroller.min.js' %}"></script> <!-- nano scroller -->

<script src="{% static 'assets/plugins/dropdown.js/jquery.dropdown.js' %}"></script> <!-- Fancy Dropdowns -->
<script src="{% static 'assets/plugins/bootstrap-material-design/js/material.min.js' %}"></script>
<!-- Bootstrap Material -->
<script src="{% static 'assets/plugins/bootstrap-material-design/js/ripples.min.js' %}"></script>
<!-- Bootstrap Material -->

<script src="{% static 'assets/js/application.js' %}"></script>
<script src="{% static 'assets/demo/demo.js' %}"></script>
<script src="{% static 'assets/demo/demo-switcher.js' %}"></script>

<!-- End loading site level scripts -->

<!-- Load page level scripts-->



<script src="{% static 'assets/plugins/form-daterangepicker/moment.min.js' %}"></script>
<!-- Moment.js for Date Range Picker -->

<!-- Date Range Picker -->
<script src="{% static 'assets/plugins/bootstrap-datepicker/bootstrap-datepicker.js' %}"></script>
<!-- Datepicker -->
<!-- <script src="assets/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js"></script> -->
<!-- DateTime Picker -->
<!-- Initialize scripts for this page-->
<script src="{% static 'smart-selects/admin/js/bindfields.js' %}"></script>
<script src="{% static 'smart-selects/admin/js/chainedfk.js' %}"></script>
<!-- End loading page level scripts-->
<script src="{% static 'assets/plugins/form-daterangepicker/moment.min.js' %}"></script>
<!-- Moment.js for Date Range Picker -->

<script src="{% static 'assets/plugins/form-colorpicker/js/bootstrap-colorpicker.min.js' %}"></script>            <!-- Color Picker -->

<script src="{% static 'assets/plugins/form-daterangepicker/daterangepicker.js' %}"></script>
<!-- Date Range Picker -->
<script src="{% static 'assets/plugins/bootstrap-datepicker/bootstrap-datepicker.js' %}"></script>                <!-- Datepicker -->
<script src="{% static 'assets/plugins/bootstrap-timepicker/bootstrap-timepicker.js' %}"></script>                <!-- Timepicker -->
<script src="{% static 'assets/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js' %}"></script> <!-- DateTime Picker -->

<script src="{% static 'assets/plugins/clockface/js/clockface.js' %}"></script>                                    <!-- Clockface -->

{% block js_extra %}
{% endblock %}

</body>
</html>

templates/sidebar_menu.html
<ul class="acc-menu">

    <li class="nav-separator"><span>Menu de navegacion</span></li>

    <li>
        <a class="withripple" href="{% url 'main:inicio' %}">
            <span class="icon">
		        <i class="material-icons">home</i>
            </span>
            <span>Inicio</span>
            <div class="ripple-container"></div>
        </a>
    </li>

    <li class="hasChild"><a class="withripple" href="javascript:;">
        <span class="icon">
            <i class="fa fa-graduation-cap"></i>
        </span>
        <span>Educacion</span>
        <div class="ripple-container"></div>
    </a>
        <ul class="acc-menu">
            <li><a class="withripple" href="{% url 'personas:lista_grados_escolaridad' %}">Grados de escolaridad</a>
            </li>
            <li><a class="withripple" href="{% url 'personas:lista_titulos_grado' %}">Titulos de grado</a></li>
            <li><a class="withripple" href="{% url 'personas:lista_tipos_formacion_complementaria' %}">Formacion complementaria</a></li>
            <!--<li><a class="withripple" href="{% url 'habilidades_blandas:lista_habilidades_blandas' %}">Habilidades Blandas (ok)</a></li>-->
            <li><a class="withripple" href="{% url 'habilidades_blandas:lista_capacitacion' %}">Capacitacion</a></li>
        </ul>
    </li>

    <li class="hasChild"><a class="withripple" href="javascript:;">
        <span class="icon">
            <i class="material-icons">location_on</i>
        </span>
        <span>Infraestructura</span>
        <div class="ripple-container"></div>
    </a>
        <ul class="acc-menu">
            <li><a class="withripple" href="{% url 'personas:lista_tipos_manzana' %}">Tipos de manzana</a></li>
            <li><a class="withripple" href="{% url 'personas:lista_tipos_vivienda' %}">Tipos de vivienda</a></li>
            <li><a class="withripple" href="{% url 'personas:lista_manzanas' %}">Manzanas</a></li>
        </ul>
    </li>

    <li>
        <a class="withripple" href="{% url 'personas:lista_casas' %}"><span class="icon">
		    <i class="material-icons">favorite_border</i></span>
            <span>Casas</span>
            <div class="ripple-container"></div>
        </a>
    </li>

    <li>
        <a class="withripple" href="{% url 'personas:lista_personas' %}"><span class="icon">
		    <i class="material-icons">accessibility</i></span>
            <span>Personas</span>
            <div class="ripple-container"></div>
        </a>
    </li>

    <li class="hasChild"><a class="withripple" href="javascript:;">
        <span class="icon">
            <i class="material-icons">account_circle</i>
        </span>
        <span>Empleabilidad</span>
        <div class="ripple-container"></div>
    </a>
        <ul class="acc-menu">
            <li><a class="withripple" href="{% url 'empleabilidad:lista_vacantes' %}">Vacantes</a></li>
            <li>
                <a class="withripple" href="{% url 'empleabilidad:lista_formaciones_trabajo' %}">
                    Formacion para el trabajo
                </a>
            </li>
        </ul>
    </li>

    <li class="hasChild">
        <a class="withripple" href="javascript:;">
            <span class="icon">
                <i class="material-icons">local_atm</i>
            </span>
            <span>Emprendimiento</span>
            <div class="ripple-container"></div>
        </a>
        <ul class="acc-menu">
            <li><a class="withripple" href="{% url 'emprendimiento:lista_tipo_negocio' %}">Tipos de negocio</a></li>
            <li><a class="withripple" href="{% url 'emprendimiento:lista_tipo_unidad_productiva' %}">Unidades Productivas</a></li>
            <li><a class="withripple" href="{% url 'emprendimiento:lista_sectores' %}">Sectores</a></li>
            <li><a class="withripple" href="{% url 'emprendimiento:lista_negocio' %}">Negocios</a></li>
            <li><a class="withripple" href="{% url 'emprendimiento:lista_empresa' %}">Empresas</a></li>
            <li><a class="withripple" href="{% url 'emprendimiento:lista_emprendimiento' %}">Emprendimientos</a></li>
            <li><a class="withripple" href="{% url 'emprendimiento:lista_oportunidad_comercial' %}">Oportunidades Comerciales</a></li>
            <li><a class="withripple" href="{% url 'emprendimiento:lista_fortalecimiento_empresarial' %}">Fortalecimiento Empresarial</a></li>
        </ul>
    </li>

</ul>