apps/api/personas/urls.py
from django.conf.urls import url, include
from rest_framework import routers

router = routers.DefaultRouter()

urlpatterns = [

]

apps/personas/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

   # tipos de formacion complementaria

    url(r'^crear-tipo-formacion-complementaria/',
        views.TipoFormacionComplementariaCreateView.as_view(),
        name='crear_tipo_formacion_complementaria'),

    url(r'^editar-tipo-formacion-complementaria/(?P<pk>\d+)/',
        views.TipoFormacionComplementariaUpdateView.as_view(),
        name='editar_tipo_formacion_complementaria'),

    url(r'^lista-tipos-formacion-complementaria/',
        views.TipoFormacionComplementariaListView.as_view(),
        name='lista_tipos_formacion_complementaria'),

    # grados de escolaridad

    url(r'^crear-grado-escolaridad/',
        views.GradoEscolaridadCreateView.as_view(),
        name='crear_grado_escolaridad'),

    url(r'^editar-grado-escolaridad/(?P<pk>\d+)/',
        views.GradoEscolaridadUpdateView.as_view(),
        name='editar_grado_escolaridad'
        ),

    url(r'^lista-grados-escolaridad/',
        views.GradoEscolaridadListView.as_view(),
        name='lista_grados_escolaridad'),

    # titulos de grado

    url(r'^crear-titulo-grado/',
        views.TituloGradoCreateView.as_view(),
        name='crear_titulo_grado'),

    url(r'^editar-titulo-grado/(?P<pk>\d+)/',
        views.TituloGradoUpdateView.as_view(),
        name='editar_titulo_grado'),

    url(r'^lista-titulos-grado/',
        views.TituloGradoListView.as_view(),
        name='lista_titulos_grado'),

    # tipos de manzana

    url(r'^crear-tipo-manzana/',
        views.TipoManzanaCreateView.as_view(),
        name='crear_tipo_manzana'),

    url(r'^editar-tipo-manzana/(?P<pk>\d+)/',
        views.TipoManzanaUpdateView.as_view(),
        name='editar_tipo_manzana'),

    url(r'^lista-tipos-manzana/',
        views.TipoManzanaListView.as_view(),
        name='lista_tipos_manzana'),

    # tipos de vivienda

    url(r'^crear-tipo-vivienda/',
        views.TipoViviendaCreateView.as_view(),
        name='crear_tipo_vivienda'),

    url(r'^editar-tipo-vivienda/(?P<pk>\d+)/',
        views.TipoViviendaUpdateView.as_view(),
        name='editar_tipo_vivienda'),

    url(r'^lista-tipos-vivienda/',
        views.TipoViviendaListView.as_view(),
        name='lista_tipos_vivienda'),

    # manzanas

    url(r'^crear-manzana/',
        views.ManzanaCreateView.as_view(),
        name='crear_manzana'),

    url(r'^editar-manzana/(?P<pk>\d+)/',
        views.ManzanaUpdateView.as_view(),
        name='editar_manzana'),

    url(r'^lista-manzanas/',
        views.ManzanaListView.as_view(),
        name='lista_manzanas'),

    # casas

    url(r'^crear-casa/',
        views.CasaCreateView.as_view(),
        name='crear_casa'),

    url(r'^editar-casa/(?P<pk>\d+)/',
            views.CasaUpdateView.as_view(),
        name='editar_casa'),

    url(r'^lista-casas/',
        views.CasaListView.as_view(),
        name='lista_casas'),

    # personas

    url(r'^crear-persona/',
        views.crear_persona,
        name='crear_persona'),

    url(r'^editar-persona/(?P<pk>\d+)/',
        views.editar_persona,
        name='editar_persona'),

    url(r'^lista-personas/',
        views.PersonasListView.as_view(),
        name='lista_personas'),

    url(r'^detalle-persona/(?P<pk>\d+)/',
        views.PersonaDetailView.as_view(),
        name='detalle_persona'),


]

villas2/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from . import settings as base
from apps.main import views
from apps.utils import errors

urlpatterns = [
    url(r'^$', views.log_in, name='entrar'),
    url(r'^salir/', views.salir, name='salir'),
    url(r'^admin/', admin.site.urls),
    url(r'^chaining/', include('smart_selects.urls')),
    # apps
    url(r'^empleabilidad/', include('apps.empleabilidad.urls', namespace='empleabilidad')),
    url(r'^emprendimiento/', include('apps.emprendimiento.urls', namespace='emprendimiento')),
    url(r'^habilidades_blandas/', include('apps.habilidades_blandas.urls', namespace='habilidades_blandas')),
    url(r'^main/', include('apps.main.urls', namespace='main')),
    url(r'^personas/', include('apps.personas.urls', namespace='personas')),

] + static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)

handler400 = errors.error400
handler403 = errors.error403
handler404 = errors.error404
handler500 = errors.error500

apps/personas/forms.py
from django import forms
from django.forms import models as models_form
from easy_select2 import Select2

from . import models
from apps.utils import forms as utils, constants


class GradoEscolaridadForm(utils.BaseFormAllFields):
    title = 'Grado de escolaridad'

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.GradoEscolaridad


class TituloGradoForm(utils.BaseFormAllFields):
    title = 'Titulo de grado'

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.TituloGrado


class TipoViviendaForm(utils.BaseFormAllFields):
    title = 'Tipo de vivienda'

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.TipoVivienda


class TipoManzanaForm(utils.BaseFormAllFields):
    title = 'Tipo de manzana'

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.TipoManzana


class ManzanaForm(utils.BaseFormAllFields):
    title = 'Manzana'

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.Manzana


class CasaForm(utils.BaseFormAllFields):
    title = 'Casa'
    numero_manzana = forms.ModelChoiceField(
        queryset=models.Manzana.objects.all(),
        widget=Select2()
    )

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.Casa


class PersonaForm(utils.BaseFormAllFields):
    title = 'Persona'
    fecha_ingreso = forms.DateField(input_formats=constants.INPUT_FORMATS)
    widget = forms.FileInput
    hoja_de_vida = forms.FileField(widget=widget)

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.Persona


class ExperienciaLaboralForm(utils.BaseFormAllFields):
    title = 'Experiencia Laboral'

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.ExperienciaLaboralPersona


def get_experiencia_laboral_persona_formset(form,
                                            formset=models_form.BaseInlineFormSet,
                                            **kwargs):
    return models_form.inlineformset_factory(
        models.Persona,
        models.ExperienciaLaboralPersona,
        form,
        formset,
        **kwargs
    )


class TipoFormacionComplementariaForm(utils.BaseFormAllFields):
    title = 'Tipo de formacion'

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.TipoFormacionComplementaria


class FormacionComplementariaForm(utils.BaseFormAllFields):
    title = 'Formacion Complementaria'

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.FormacionComplementariaPersona


def get_formacion_complementaria_persona_formset(form,
                                            formset=models_form.BaseInlineFormSet,
                                            **kwargs):
    return models_form.inlineformset_factory(
        models.Persona,
        models.FormacionComplementariaPersona,
        form,
        formset,
        **kwargs
    )

apps/api/personas/views.py
from rest_framework import generics
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

apps/personas/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from apps.empleabilidad.forms import get_vacante_persona_formset as vacante_formset, \
    get_formacion_trabajo_persona_formset  as formacion_trabajo_formset
from apps.habilidades_blandas.forms import get_habilidad_blanda_persona_formset as habilidad_formset
from apps.utils import views
from . import models
from . import forms
# Create your views here.


class GradoEscolaridadBaseView(object):
    model = models.GradoEscolaridad
    success_url = reverse_lazy('personas:lista_grados_escolaridad')
    form_class = forms.GradoEscolaridadForm


class GradoEscolaridadCreateView(GradoEscolaridadBaseView, views.BaseCreateView):
    pass


class GradoEscolaridadUpdateView(GradoEscolaridadBaseView, views.BaseUpdateView):
    pass


class GradoEscolaridadListView(views.BaseListViewDinamicHeader):
    HEADER = ('id', 'nombre grado', 'personas')
    model = models.GradoEscolaridad
    template_name = 'apps/personas/grado_escolaridad_list.html'


class TituloGradoBaseView(object):
    model = models.TituloGrado
    success_url = reverse_lazy('personas:lista_titulos_grado')
    form_class = forms.TituloGradoForm


class TituloGradoCreateView(TituloGradoBaseView, views.BaseCreateView):
    pass


class TituloGradoUpdateView(TituloGradoBaseView, views.BaseUpdateView):
    pass


class TituloGradoListView(views.BaseListViewDinamicHeader):
    HEADER = ('id', 'nombre titulo', 'grado de escolaridad', 'personas')
    model = models.TituloGrado
    template_name = 'apps/personas/titulo_grado_list.html'


class TipoManzanaBaseView(object):
    model = models.TipoManzana
    success_url = reverse_lazy('personas:lista_tipos_manzana')
    form_class = forms.TipoManzanaForm


class TipoManzanaCreateView(TipoManzanaBaseView, views.BaseCreateView):
    pass


class TipoManzanaUpdateView(TipoManzanaBaseView, views.BaseUpdateView):
    pass


class TipoManzanaListView(views.BaseListViewDinamicHeader):
    HEADER = ('id', 'nombre', 'personas', 'casas')
    model = models.TipoManzana
    template_name = 'apps/personas/tipo_manzana_list.html'


class TipoViviendaBaseView(object):
    model = models.TipoVivienda
    form_class = forms.TipoViviendaForm
    success_url = reverse_lazy('personas:lista_tipos_vivienda')


class TipoViviendaCreateView(TipoViviendaBaseView, views.BaseCreateView):
    pass


class TipoViviendaUpdateView(TipoViviendaBaseView, views.BaseUpdateView):
    pass


class TipoViviendaListView(views.BaseListViewDinamicHeader):
    HEADER = ('id', 'nombre', 'personas', 'casas')
    model = models.TipoVivienda
    template_name = 'apps/personas/tipo_vivienda_list.html'


class ManzanaBaseView(object):
    model = models.Manzana
    form_class = forms.ManzanaForm
    success_url = reverse_lazy('personas:lista_manzanas')


class ManzanaCreateView(ManzanaBaseView, views.BaseCreateView):
    pass


class ManzanaUpdateView(ManzanaBaseView, views.BaseUpdateView):
    pass


class ManzanaListView(views.BaseListViewDinamicHeader):
    HEADER = ('numero', 'tipo', 'personas', 'casas')
    model = models.Manzana
    template_name = 'apps/personas/manzana_list.html'


class CasaBaseView(object):
    model = models.Casa
    form_class = forms.CasaForm
    success_url = reverse_lazy('personas:lista_casas')


class CasaCreateView(CasaBaseView, views.BaseCreateView):
    pass


class CasaUpdateView(CasaBaseView, views.BaseUpdateView):
    pass


class CasaListView(views.BaseListViewDinamicHeader):
    HEADER = ('# casa', 'direccion', 'tipo de manzana',
              '# manzana', 'tipo de vivienda', 'telefonos', 'personas')
    model = models.Casa
    template_name = 'apps/personas/casa_list.html'


@login_required
def crear_persona(request):
    form_class = forms.PersonaForm
    experienciaFormset = forms.get_experiencia_laboral_persona_formset(form_class, extra=1, can_delete=True)
    formacionFormset = forms.get_formacion_complementaria_persona_formset(form_class, extra=1, can_delete=True)
    vacanteFormset = vacante_formset(form_class, extra=2, can_delete=True)
    formacionTrabajoFormset = formacion_trabajo_formset(form_class, extra=2, can_delete=True)
    habilidadBlandaFormset = habilidad_formset(form_class, extra=2, can_delete=True)
    persona = models.Persona()
    form = forms.PersonaForm(request.POST or None, instance=persona)
    formset_1 = experienciaFormset(request.POST or None, instance=persona)
    formset_2 = formacionFormset(request.POST or None, instance=persona)
    formset_3 = vacanteFormset(request.POST or None, instance=persona)
    formset_4 = formacionTrabajoFormset(request.POST or None, instance=persona)
    formset_5 = habilidadBlandaFormset(request.POST or None, instance=persona)
    if request.POST:
        if form.is_valid() and formset_1.is_valid() and formset_2.is_valid()\
                and formset_3.is_valid() and formset_4.is_valid() and formset_5.is_valid():
            form.save()
            formset_1.save()
            formset_2.save()
            formset_3.save()
            formset_4.save()
            formset_5.save()
            return redirect('personas:lista_personas')

    context = {
        'form': form,
        'formset_1': formset_1,
        'formset_2': formset_2,
        'formset_3': formset_3,
        'formset_4': formset_4,
        'formset_5': formset_5,
        'action': 'Crear Persona'
    }
    return render(request, 'apps/personas/persona/base_form.html', context)


@login_required
def editar_persona(request, **kwargs):
    form_class = forms.PersonaForm
    experienciaFormset = forms.get_experiencia_laboral_persona_formset(form_class, extra=0, can_delete=True)
    formacionFormset = forms.get_formacion_complementaria_persona_formset(form_class, extra=0, can_delete=True)
    vacanteFormset = vacante_formset(form_class, extra=0, can_delete=True)
    formacionTrabajoFormset = formacion_trabajo_formset(form_class, extra=0, can_delete=True)
    habilidadBlandaFormset = habilidad_formset(form_class, extra=0, can_delete=True)
    pk = kwargs.get('pk')
    persona = models.Persona.objects.get(id=pk)
    form = forms.PersonaForm(request.POST or None, instance=persona)
    formset_1 = experienciaFormset(request.POST or None, instance=persona)
    formset_2 = formacionFormset(request.POST or None, instance=persona)
    formset_3 = vacanteFormset(request.POST or None, instance=persona)
    formset_4 = formacionTrabajoFormset(request.POST or None, instance=persona)
    formset_5 = habilidadBlandaFormset(request.POST or None, instance=persona)
    if request.POST:
        if form.is_valid() and formset_1.is_valid() and formset_2.is_valid() \
                and formset_3.is_valid() and formset_4.is_valid() and formset_5.is_valid():
            form.save()
            formset_1.save()
            formset_2.save()
            formset_3.save()
            formset_4.save()
            formset_5.save()
            return redirect('personas:lista_personas')

    context = {
        'form': form,
        'formset_1': formset_1,
        'formset_2': formset_2,
        'formset_3': formset_3,
        'formset_4': formset_4,
        'formset_5': formset_5,
        'action': 'Modificar Persona'
    }
    return render(request, 'apps/personas/persona/base_form.html', context)


class TipoFormacionComplementariaBaseView(object):
    model = models.TipoFormacionComplementaria
    form_class = forms.TipoFormacionComplementariaForm
    success_url = reverse_lazy('personas:lista_tipos_formacion_complementaria')


class TipoFormacionComplementariaCreateView(TipoFormacionComplementariaBaseView,
                                          views.BaseCreateView):
    pass


class TipoFormacionComplementariaUpdateView(TipoFormacionComplementariaBaseView,
                                          views.BaseUpdateView):
    pass


class TipoFormacionComplementariaListView(views.BaseListViewDinamicHeader):
    HEADER = ('id', 'tipo de formacion complementaria')
    model = models.TipoFormacionComplementaria
    template_name = 'apps/personas/tipo_formacion_complementaria_list.html'


class PersonasListView(views.BaseListViewDinamicHeader):
    HEADER = ('Identificacion', 'Tipo de Documento', 'Nombre', 'Apellido',
              'Telefono', 'Direccion')
    model = models.Persona
    template_name = 'apps/personas/lista_persona.html'


class PersonaDetailView(views.BaseDetailView):
    model = models.Persona
    template_name = 'apps/personas/persona/detalle_persona.html'

templates/apps/personas/casa_list.html
{% extends 'apps/base/list_base.html' %}
{% block title_table %}
    Lista de casas
{% endblock %}

{% block content_main_table_data %}
    <tr class="odd" role="row">
        <td class="center text-center">
            {{ obj.numero_casa }}
        </td>
        <th class="text-center">
            {{ obj.direccion_casa }}
        </th>
        <td class="center text-center">
            {{ obj.tipo_manzana }}
        </td>
        <td class="text-center">
            {{ obj.numero_manzana }}
        </td>
        <td class="text-center">
            {{ obj.tipo_vivienda }}
        </td>
        <td class="text-center">
            {{ obj.numero_telefono }}
            {% if obj.numero_telefono_2 %}
                - {{ obj.numero_telefono_2 }}
            {% endif %}
        </td>
        <td class="center text-center">
            {{ obj.personas.count }}
        </td>
        <td class="center text-center">
            <a href="{{ obj.get_update_url }}" class="btn btn-info btn-raised waves-effect btn-xs"
               data-toggle="tooltip" data-placement="top" title=""
               data-original-title="Modificar">
                <i class="fa fa-pencil"></i>
            </a>
        </td>
    </tr>
{% endblock %}

{% block fab %}
<a href="{% url 'personas:crear_casa' %}" class="btn btn-primary btn-fab demo-switcher-fab"
        data-toggle="tooltip" data-placement="top"
        title="Crear casa">
    <i class="material-icons">add</i>
</a>
{% endblock %}

templates/apps/personas/grado_escolaridad_list.html
{% extends 'apps/base/list_base.html' %}
{% block title_table %}
    Lista de grados de escolaridad
{% endblock %}

{% block content_main_table_data %}
    <tr class="odd" role="row">
        <td class="center text-center">
            {{ obj.id }}
        </td>
        <td class="center text-center">
            {{ obj.nombre_grado_escolaridad }}
        </td>
        <td class="center text-center">
            {{ obj.personas.count }}
        </td>
        <td class="center text-center">
            <a href="{{ obj.get_update_url }}" class="btn btn-info btn-raised waves-effect btn-xs"
               data-toggle="tooltip" data-placement="top" title=""
               data-original-title="Modificar">
                <i class="fa fa-pencil"></i>
            </a>
        </td>
    </tr>
{% endblock %}

{% block fab %}
<a href="{% url 'personas:crear_grado_escolaridad' %}" class="btn btn-primary btn-fab demo-switcher-fab"
        data-toggle="tooltip" data-placement="top"
        title="Crear grado de escolaridad">
    <i class="material-icons">add</i>
</a>
{% endblock %}

templates/apps/personas/lista_persona.html
{% extends 'apps/base/list_base.html' %}
{% block title_table %}
    Lista de personas
{% endblock %}

{% block content_main_table_data %}
    <tr class="odd" role="row">
        <td class="center text-center">
            {{ obj.identificacion }}
        </td>
        <th class="text-center">
            {{ obj.tipo_documento_identificacion }}
        </th>
        <td class="center text-center">
            {{ obj.get_full_name }}
        </td>
        <td class="text-center">
            {{ obj.telefono_1 }}
        </td>
        <td class="text-center">
            {{ obj.get_vivienda }}
        </td>
        <td class="center text-center">
            {{ obj.personas.count }}
        </td>
        <td class="center text-center">
            <a href="{{ obj.get_update_url }}" class="btn btn-info btn-raised waves-effect btn-xs"
               data-toggle="tooltip" data-placement="top" title=""
               data-original-title="Modificar">
                <i class="fa fa-pencil"></i>
            </a>
            <a href="{{ obj.get_absolute_url }}" class="btn btn-success btn-raised waves-effect btn-xs"
               data-toggle="tooltip" data-placement="top" title=""
               data-original-title="Ver Perfil">
                <i class="fa fa-eye"></i>
            </a>
        </td>
    </tr>
{% endblock %}

{% block fab %}
<a href="{% url 'personas:crear_persona' %}" class="btn btn-primary btn-fab demo-switcher-fab"
        data-toggle="tooltip" data-placement="top"
        title="Crear Persona">
    <i class="material-icons">add</i>
</a>
{% endblock %}

templates/apps/personas/manzana_list.html
{% extends 'apps/base/list_base.html' %}
{% block title_table %}
    Lista de manzanas
{% endblock %}

{% block content_main_table_data %}
    <tr class="odd" role="row">
        <td class="center text-center">
            {{ obj.numero_manzana }}
        </td>
        <th class="text-center">
            {{ obj.tipo_manzana }}
        </th>
        <td class="center text-center">
            {{ obj.personas.count }}
        </td>
        <td class="center text-center">
            {{ obj.casas.count }}
        </td>
        <td class="center text-center">
            <a href="{{ obj.get_update_url }}" class="btn btn-info btn-raised waves-effect btn-xs"
               data-toggle="tooltip" data-placement="top" title=""
               data-original-title="Modificar">
                <i class="fa fa-pencil"></i>
            </a>
        </td>
    </tr>
{% endblock %}

{% block fab %}
<a href="{% url 'personas:crear_manzana' %}" class="btn btn-primary btn-fab demo-switcher-fab"
        data-toggle="tooltip" data-placement="top"
        title="Crear manzana">
    <i class="material-icons">add</i>
</a>
{% endblock %}

templates/apps/personas/tipo_formacion_complementaria_list.html
{% extends 'apps/base/list_base.html' %}
{% block title_table %}
    Lista de tipos de formacion complementaria
{% endblock %}

{% block content_main_table_data %}
    <tr class="odd" role="row">
        <td class="center text-center">
            {{ obj.id }}
        </td>
        <td class="center text-center">
            {{ obj.nombre }}
        </td>
        <td class="center text-center">
            <a href="{{ obj.get_update_url }}" class="btn btn-info btn-raised waves-effect btn-xs"
               data-toggle="tooltip" data-placement="top" title=""
               data-original-title="Modificar">
                <i class="fa fa-pencil"></i>
            </a>
        </td>
    </tr>
{% endblock %}

{% block fab %}
<a href="{% url 'personas:crear_tipo_formacion_complementaria' %}" class="btn btn-primary btn-fab demo-switcher-fab"
        data-toggle="tooltip" data-placement="top"
        title="Crear tipo de formacion complementaria">
    <i class="material-icons">add</i>
</a>
{% endblock %}

templates/apps/personas/tipo_manzana_list.html
{% extends 'apps/base/list_base.html' %}
{% block title_table %}
    Lista de tipos de manzanas
{% endblock %}

{% block content_main_table_data %}
    <tr class="odd" role="row">
        <td class="center text-center">
            {{ obj.id }}
        </td>
        <td class="center text-center">
            {{ obj.nombre_tipo_manzana }}
        </td>
        <td class="center text-center">
            {{ obj.personas.count }}
        </td>
        <td class="center text-center">
            {{ obj.casas.count }}
        </td>
        <td class="center text-center">
            <a href="{{ obj.get_update_url }}" class="btn btn-info btn-raised waves-effect btn-xs"
               data-toggle="tooltip" data-placement="top" title=""
               data-original-title="Modificar">
                <i class="fa fa-pencil"></i>
            </a>
        </td>
    </tr>
{% endblock %}

{% block fab %}
<a href="{% url 'personas:crear_tipo_manzana' %}" class="btn btn-primary btn-fab demo-switcher-fab"
        data-toggle="tooltip" data-placement="top"
        title="Crear tipo de manzana">
    <i class="material-icons">add</i>
</a>
{% endblock %}

templates/apps/personas/tipo_vivienda_list.html
{% extends 'apps/base/list_base.html' %}
{% block title_table %}
    Lista de tipos de viviendas
{% endblock %}

{% block content_main_table_data %}
    <tr class="odd" role="row">
        <td class="center text-center">
            {{ obj.id }}
        </td>
        <td class="center text-center">
            {{ obj.nombre_tipo_vivienda }}
        </td>
        <td class="center text-center">
            {{ obj.personas.count }}
        </td>
        <td class="center text-center">
            {{ obj.casas.count }}
        </td>
        <td class="center text-center">
            <a href="{{ obj.get_update_url }}" class="btn btn-info btn-raised waves-effect btn-xs"
               data-toggle="tooltip" data-placement="top" title=""
               data-original-title="Modificar">
                <i class="fa fa-pencil"></i>
            </a>
        </td>
    </tr>
{% endblock %}

{% block fab %}
<a href="{% url 'personas:crear_tipo_vivienda' %}" class="btn btn-primary btn-fab demo-switcher-fab"
        data-toggle="tooltip" data-placement="top"
        title="Crear tipo de vivienda">
    <i class="material-icons">add</i>
</a>
{% endblock %}

templates/apps/personas/titulo_grado_list.html
{% extends 'apps/base/list_base.html' %}
{% block title_table %}
    Lista de titulos academicos
{% endblock %}

{% block content_main_table_data %}
    <tr class="odd" role="row">
        <td class="center text-center">
            {{ obj.id }}
        </td>
        <td class="center text-center">
            {{ obj.nombre_titulo }}
        </td>
        <th class="text-center">
            {{ obj.grado_escolaridad }}
        </th>
        <td class="center text-center">
            {{ obj.personas.count }}
        </td>
        <td class="center text-center">
            <a href="{{ obj.get_update_url }}" class="btn btn-info btn-raised waves-effect btn-xs"
               data-toggle="tooltip" data-placement="top" title=""
               data-original-title="Modificar">
                <i class="fa fa-pencil"></i>
            </a>
        </td>
    </tr>
{% endblock %}

{% block fab %}
<a href="{% url 'personas:crear_titulo_grado' %}" class="btn btn-primary btn-fab demo-switcher-fab"
        data-toggle="tooltip" data-placement="top"
        title="Crear titulo academico">
    <i class="material-icons">add</i>
</a>
{% endblock %}