apps/api/emprendimiento/urls.py
from django.conf.urls import url, include
from rest_framework import routers

router = routers.DefaultRouter()

urlpatterns = [

]

apps/emprendimiento/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    url(r'^crear-tipo-negocio/',
        views.TipoNegocioCreateView.as_view(),
        name='crear_tipo_negocio'),

    url(r'^editar-tipo-negocio/(?P<pk>\d+)/',
        views.TipoNegocioUpdateView.as_view(),
        name='editar_tipo_negocio'),

    url(r'^lista-tipo-negocio/',
        views.TipoNegocioListView.as_view(),
        name='lista_tipo_negocio'),

    url(r'^crear-tipo-unidad-productiva/',
        views.TipoUnidadProductivaCreateView.as_view(),
        name='crear_tipo_unidad_productiva'),

    url(r'^editar-tipo-unidad-productiva/(?P<pk>\d+)',
        views.TipoUnidadProductivaUpdateView.as_view(),
        name='editar_tipo_unidad_productiva'),

    url(r'^lista-tipo-unidad-productiva/',
        views.TipoUnidadProductivaListView.as_view(),
        name='lista_tipo_unidad_productiva'),

    url(r'^crear-sector/',
        views.SectorCreateView.as_view(),
        name='crear_sector'),

    url(r'^editar-sector/(?P<pk>\d+)/',
        views.SectorUpdateView.as_view(),
        name='editar_sector'),

    url(r'^lista-sectores/',
        views.SectorListView.as_view(),
        name='lista_sectores'),

    url(r'^crear-negocios/',
        views.NegocioCreateView.as_view(),
        name='crear_negocio'),

    url(r'^editar-negocio/(?P<pk>\d+)',
        views.NegocioUpdateView.as_view(),
        name='editar_negocio'),

    url(r'^lista-negocio/',
        views.NegocioListView.as_view(),
        name='lista_negocio'),

    url(r'^crear-empresa/',
        views.EmpresaCreateView.as_view(),
        name='crear_empresa'),

    url(r'^editar-empresa/(?P<pk>\d+)',
        views.EmpresaUpdateView.as_view(),
        name='editar_empresa'),

    url(r'^lista-empresa/',
        views.EmpresaListView.as_view(),
        name='lista_empresa'),

    url(r'^crear-emprendimiento/',
        views.EmprendimientoCreateView.as_view(),
        name='crear_emprendimiento'),

    url(r'^editar-empresa/(?P<pk>\d+)',
        views.EmpresaUpdateView.as_view(),
        name='editar_empresa'),

    url(r'^lista-emprendimiento/',
        views.EmprendimientoListView.as_view(),
        name='lista_emprendimiento'),

    url(r'^crear-oportunidad-comercial/',
        views.OportunidadComercialCreateView.as_view(),
        name='crear_oportunidad_comercial'),

    url(r'^editar-oportunidad-comercial/(?P<pk>\d+)',
        views.OportuniadadComercialUpdateView.as_view(),
        name='editar_emprendimiento'),

    url(r'^lista-oportunidad-comercial/',
        views.OportunidadComercialListView.as_view(),
        name='lista_oportunidad_comercial'),

    url(r'^crear-fortalecimiento-empresarial/',
        views.FortalecimientoEmpresarialCreateView.as_view(),
        name='crear_fortalecimiento_empresarial'),

    url(r'^editar_fortalecimiento_empresarial/(?P<pk>\d+)',
        views.FortalecimientoEmpresarialUpdateView.as_view(),
        name='editar_fortalecimiento_empresarial'),

    url(r'^lista-fortalecimiento-empresarial/',
        views.FortalecimientoEmpresarialListView.as_view(),
        name='lista_fortalecimiento_empresarial'),
]

villas2/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from . import settings as base
from apps.main import views
from apps.utils import errors

urlpatterns = [
    url(r'^$', views.log_in, name='entrar'),
    url(r'^salir/', views.salir, name='salir'),
    url(r'^admin/', admin.site.urls),
    url(r'^chaining/', include('smart_selects.urls')),
    # apps
    url(r'^empleabilidad/', include('apps.empleabilidad.urls', namespace='empleabilidad')),
    url(r'^emprendimiento/', include('apps.emprendimiento.urls', namespace='emprendimiento')),
    url(r'^habilidades_blandas/', include('apps.habilidades_blandas.urls', namespace='habilidades_blandas')),
    url(r'^main/', include('apps.main.urls', namespace='main')),
    url(r'^personas/', include('apps.personas.urls', namespace='personas')),

] + static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)

handler400 = errors.error400
handler403 = errors.error403
handler404 = errors.error404
handler500 = errors.error500

apps/emprendimiento/models.py
from django.db import models
from django.urls import reverse_lazy
from smart_selects.db_fields import ChainedForeignKey


# Create your models here.


class BaseUpdateUrl(object):
    attr_query = None

    def get_update_url(self):
        return reverse_lazy('emprendimiento:editar_{}'.format(self.attr_query), kwargs={'pk': self.pk})


class BaseName(models.Model, BaseUpdateUrl):
    nombre = models.CharField(max_length=150, unique=True)
    attr_query = None

    class Meta:
        abstract = True

    def __str__(self):
        return self.nombre

    def get_attr_queryset_value(self):
        return {self.attr_query: self}

    def negocios(self):
        return Negocio.objects.filter(**self.get_attr_queryset_value())


class TipoNegocio(BaseName, BaseUpdateUrl):
    attr_query = 'tipo_negocio'

    class Meta:
        verbose_name = 'Tipo de negocio'
        verbose_name_plural = 'Tipos de negocio'


class TipoUnidadProductiva(BaseName, BaseUpdateUrl):
    attr_query = 'tipo_unidad_productiva'

    class Meta:
        verbose_name = 'Tipo de unidad productiva'
        verbose_name_plural = 'Tipos de unidades productivas'


class Sector(BaseName, BaseUpdateUrl):
    attr_query = 'sector'

    class Meta:
        verbose_name = 'Sector'
        verbose_name_plural = 'Sectores'


class Negocio(models.Model, BaseUpdateUrl):

    attr_query = 'negocio'

    nombre = models.CharField(max_length=100, unique=True)
    direccion = models.CharField(max_length=100)
    propietario = models.ForeignKey('personas.Persona')
    tipo_negocio = models.ForeignKey(TipoNegocio)

    class Meta:
        verbose_name = 'Negocio'
        verbose_name_plural = 'Negocios'

    def __str__(self):
        return '{} de {}, tipo de negocio : {}'.format(self.nombre, self.propietario, self.tipo_negocio)


class Empresa(BaseName, BaseUpdateUrl):
    attr_query = 'empresa'

    class Meta:
        verbose_name = 'Empresa'
        verbose_name_plural = 'Empresas'


class Emprendimiento(models.Model, BaseUpdateUrl):
    attr_query = 'emprendimiento'

    persona = models.ForeignKey('personas.Persona')
    tipo_negocio = models.ForeignKey(TipoNegocio)
    negocio = ChainedForeignKey(
        Negocio,
        chained_field='tipo_negocio',
        chained_model_field='tipo_negocio'
    )
    ficha_caracterizacion = models.BooleanField(default=False)
    ingreso_promedio_ventas = models.PositiveIntegerField(default=0)
    ingreso_promedio_ventas_finales = models.PositiveIntegerField(default=0)
    tipo_unidad_productova = models.ForeignKey(TipoUnidadProductiva)
    sector = models.ForeignKey(Sector)
    capital_semilla = models.PositiveIntegerField(default=0)
    inscrito_en = models.CharField(
        max_length=50,
        choices=(
            ('Fortalecimiento Empresarial', 'Fortalecimiento Empresarial'),
            ('Emprendimiento', 'Emprendimiento')
        )
    )

    class Meta:
        unique_together = ['persona', 'negocio']
        verbose_name = 'Emprendimiento'
        verbose_name_plural = 'Emprendimientos'

    def __str__(self):
        return 'emprendimiento #{},  {} a nombre de {}'.format(
            self.pk,
            self.negocio.nombre,
            self.negocio.propietario
        )


class OportunidadComercial(models.Model, BaseUpdateUrl):
    attr_query = 'oportunidad_comercial'

    negocio = models.ForeignKey(Emprendimiento)
    fecha = models.DateField()
    empresa = models.ForeignKey(Empresa)

    class Meta:
        verbose_name_plural = 'Oportunidades Comerciales'
        verbose_name = 'Oportunidad Comercial'


class FortalecimientoEmpresarial(models.Model, BaseUpdateUrl):
    attr_query = 'fortalecimiento_empresarial'

    persona = models.ForeignKey('personas.Persona')
    negocio = ChainedForeignKey(
        Negocio,
        chained_field='persona',
        chained_model_field='propietario'
    )
    emprendimiento = ChainedForeignKey(
        Emprendimiento,
        chained_field='negocio',
        chained_model_field='negocio'
    )
    rut = models.CharField(max_length=20, blank=True, null=True)
    nit = models.CharField(max_length=20, blank=True, null=True)
    camara_de_comercio = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Fortalecimiento Empresarial'
        verbose_name_plural = 'Fortalecimientos Empresariales'

apps/emprendimiento/forms.py
from django import forms
from apps.utils import forms as utils, constants
from . import models


class TipoNegocioForm(utils.BaseFormAllFields):
    title = 'Tipo Negocio'

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.TipoNegocio


class TipoUnidadProductivaForm(utils.BaseFormAllFields):
    title = 'Tipo Unidad Productiva'

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.TipoUnidadProductiva


class SectorForm(utils.BaseFormAllFields):
    title = 'Sector'

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.Sector


class NegocioForm(utils.BaseFormAllFields):
    title = 'Negocio'

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.Negocio


class EmpresaForm(utils.BaseFormAllFields):
    title = 'Empresa'

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.Empresa


class EmprendimientoForm(utils.BaseFormAllFields):
    title = 'Emprendimiento'

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.Emprendimiento


class OportunidadComercialForm(utils.BaseFormAllFields):
    title = 'Oportunidad Comercial'
    fecha = forms.DateField(input_formats=constants.INPUT_FORMATS)

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.OportunidadComercial


class FortalecimientoEmpresarialForm(utils.BaseFormAllFields):
    title = 'Fortalecimiento Empresarial'

    class Meta(utils.BaseFormAllFields.Meta):
        model = models.FortalecimientoEmpresarial

apps/api/emprendimiento/views.py
from rest_framework import generics
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

apps/emprendimiento/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from apps.utils import views
from . import models, forms
# Create your views here.


class TipoNegocioBaseView(object):
    model = models.TipoNegocio
    form_class = forms.TipoNegocioForm
    success_url = reverse_lazy('emprendimiento:lista_tipo_negocio')


class TipoNegocioCreateView(TipoNegocioBaseView, views.BaseCreateView):
    pass


class TipoNegocioUpdateView(TipoNegocioBaseView, views.BaseUpdateView):
    pass


class TipoNegocioListView(views.BaseListViewDinamicHeader):
    HEADER = ('id', 'Nombre', 'Negocios')
    model = models.TipoNegocio
    template_name = 'apps/emprendimiento/tipo_negocio_list.html'


class TipoUnidadProductivaBaseView(object):
    model = models.TipoUnidadProductiva
    form_class = forms.TipoUnidadProductivaForm
    success_url = reverse_lazy('emprendimiento:lista_tipo_unidad_productiva')


class TipoUnidadProductivaCreateView(TipoUnidadProductivaBaseView, views.BaseCreateView):
    pass


class TipoUnidadProductivaUpdateView(TipoUnidadProductivaBaseView, views.BaseUpdateView):
    pass


class TipoUnidadProductivaListView(views.BaseListViewDinamicHeader):
    HEADER = ('id', 'Nombre')
    model = models.TipoUnidadProductiva
    template_name = 'apps/emprendimiento/tipo_unidad_productiva_list.html'


class SectorBaseView(object):
    model = models.Sector
    form_class = forms.SectorForm
    success_url = reverse_lazy('emprendimiento:lista_sectores')


class SectorCreateView(SectorBaseView, views.BaseCreateView):
    pass


class SectorUpdateView(SectorBaseView, views.BaseUpdateView):
    pass


class SectorListView(views.BaseListViewDinamicHeader):
    HEADER = ('id', 'Nombre')
    model = models.Sector
    template_name = 'apps/emprendimiento/sector_list.html'


class NegocioBaseView(object):
    model = models.Negocio
    form_class = forms.NegocioForm
    success_url = reverse_lazy('emprendiemiento:lista_negocio')


class NegocioCreateView(NegocioBaseView, views.BaseCreateView):
    pass


class NegocioUpdateView(NegocioBaseView, views.UpdateView):
    pass


class NegocioListView(views.BaseListViewDinamicHeader):
    HEADER = ('id', 'Nombre', 'Direccion', 'Propietario', 'Tipo Negocio')
    model = models.Negocio
    template_name = 'apps/emprendimiento/negocio_list.html'


class EmpresasBaseView(object):
    model = models.Empresa
    form_class = forms.EmpresaForm
    success_url = reverse_lazy('emprendimiento:lista_empresa')


class EmpresaCreateView(EmpresasBaseView, views.BaseCreateView):
    pass


class EmpresaUpdateView(EmpresasBaseView, views.BaseUpdateView):
    pass


class EmpresaListView(EmpresasBaseView, views.BaseListViewDinamicHeader):
    HEADER = ('id', 'Nombre')
    model = models.Empresa
    template_name = 'apps/emprendimiento/empresa_list.html'


class EmprendimientoBaseView(object):
    model = models.Emprendimiento
    form_class = forms.EmprendimientoForm
    success_url = reverse_lazy('emprendimiento:lista_emprendimiento')


class EmprendimientoCreateView(EmprendimientoBaseView, views.BaseCreateView):
    pass


class EmprendimientoUpdateView(EmprendimientoBaseView, views.BaseUpdateView):
    pass


class EmprendimientoListView(EmprendimientoBaseView, views.BaseListViewDinamicHeader):
    HEADER = ('id', 'Persona', 'Tipo Negocio', 'Negocio', 'Ficha Caracterizacion', 'Ingreso Promedio Ventas', 'Ingreso Promedio Ventas Final', 'Tipo Unidad Productiva', 'Sector', 'Capital Semilla', 'Inscrito en:')
    model = models.Emprendimiento
    template_name = 'apps/emprendimiento/emprendimiento_list.html'


class OportunidadComercialBaseView(object):
    model = models.OportunidadComercial
    form_class = forms.OportunidadComercialForm
    sucess_url = reverse_lazy('emprendimiento:lista_oportunidad_comercial')


class OportunidadComercialCreateView(OportunidadComercialBaseView, views.BaseCreateView):
    pass


class OportuniadadComercialUpdateView(OportunidadComercialBaseView, views.BaseUpdateView):
    pass


class OportunidadComercialListView(OportunidadComercialBaseView, views.BaseListViewDinamicHeader):
    HEADER = ('id', 'Nombre', 'Negocio', 'Fecha', 'Empresa')
    model = models.OportunidadComercial
    template_name = 'apps/emprendimiento/oportunidad_comercial_list.html'


class FortalecimientoEmpresarialBaseView(object):
    model = models.FortalecimientoEmpresarial
    form_class = forms.FortalecimientoEmpresarialForm
    success_url = reverse_lazy('emprendimiento:lista_fortalecimiento_empresarial')


class FortalecimientoEmpresarialCreateView(FortalecimientoEmpresarialBaseView, views.BaseCreateView):
    pass


class FortalecimientoEmpresarialUpdateView(FortalecimientoEmpresarialBaseView, views.BaseUpdateView):
    pass


class FortalecimientoEmpresarialListView(FortalecimientoEmpresarialBaseView, views.BaseListViewDinamicHeader):
    HEADER = ('id', 'Personas', 'Tipo Negocio', 'Negocio', 'Emprendimiento', 'RUT', 'NIT', 'Camara de Comercio')
    model = models.FortalecimientoEmpresarial
    template_name = 'apps/emprendimiento/fortalecimiento_empresarial_list.html'

templates/apps/emprendimiento/emprendimiento_list.html
{% extends 'apps/base/list_base.html' %}
{% block title_table %}
    Lista de Emprendimiento
{% endblock %}

{% block content_main_table_data %}
    <tr class="odd" role="row">
        <td class="center text-center">
            {{ obj.id }}
        </td>
        <td class="center text-center">
            {{ obj.nombre }}
        </td>
        <td class="center text-center">
            {{ obj.direccion }}
        </td>
        <td class="center text-center">
            {{ obj.propietario }}
        </td>
        <td class="center text-center">
            {{ obj.tipo_negocio }}
        </td>
        <td class="center text-center">
            <a href="{{ obj.get_update_url }}" class="btn btn-info btn-raised waves-effect btn-xs"
               data-toggle="tooltip" data-placement="top" title=""
               data-original-title="Modificar">
                <i class="fa fa-pencil"></i>
            </a>
        </td>
    </tr>
{% endblock %}

{% block fab %}
<a href="{% url 'emprendimiento:crear_emprendimiento' %}" class="btn btn-primary btn-fab demo-switcher-fab"
        data-toggle="tooltip" data-placement="top"
        title="Crear Emprendimiento">
    <i class="material-icons">add</i>
</a>
{% endblock %}

templates/apps/emprendimiento/empresa_list.html
{% extends 'apps/base/list_base.html' %}
{% block title_table %}
    Lista de Empresas
{% endblock %}

{% block content_main_table_data %}
    <tr class="odd" role="row">
        <td class="center text-center">
            {{ obj.id }}
        </td>
        <td class="center text-center">
            {{ obj.nombre }}
        </td>
        <td class="center text-center">
            <a href="{{ obj.get_update_url }}" class="btn btn-info btn-raised waves-effect btn-xs"
               data-toggle="tooltip" data-placement="top" title=""
               data-original-title="Modificar">
                <i class="fa fa-pencil"></i>
            </a>
        </td>
    </tr>
{% endblock %}

{% block fab %}
<a href="{% url 'emprendimiento:crear_empresa' %}" class="btn btn-primary btn-fab demo-switcher-fab"
        data-toggle="tooltip" data-placement="top"
        title="Crear Empresa">
    <i class="material-icons">add</i>
</a>
{% endblock %}

templates/apps/emprendimiento/fortalecimiento_empresarial_list.html
{% extends 'apps/base/list_base.html' %}
{% block title_table %}
    Lista de Fortalecimiento Empresarial
{% endblock %}

{% block content_main_table_data %}
    <tr class="odd" role="row">
        <td class="center text-center">
            {{ obj.id }}
        </td>
        <td class="center text-center">
            {{ obj.personas }}
        </td>
        <td class="center text-center">
            {{ obj.negocio }}
        </td>
        <td class="center text-center">
            {{ obj.emprendimiento }}
        </td>
        <td class="center text-center">
            {{ obj.rut}}
        </td>
        <td class="center text-center">
            {{ obj.nit}}
        </td>
        <td class="center text-center">
            {{ obj.camara_de_comercio}}
        </td>
        <td class="center text-center">
            <a href="{{ obj.get_update_url }}" class="btn btn-info btn-raised waves-effect btn-xs"
               data-toggle="tooltip" data-placement="top" title=""
               data-original-title="Modificar">
                <i class="fa fa-pencil"></i>
            </a>
        </td>
    </tr>
{% endblock %}

{% block fab %}
<a href="{% url 'emprendimiento:crear_fortalecimiento_empresarial' %}" class="btn btn-primary btn-fab demo-switcher-fab"
        data-toggle="tooltip" data-placement="top"
        title="Crear Fortalecimiento Empresarial">
    <i class="material-icons">add</i>
</a>
{% endblock %}

templates/apps/emprendimiento/negocio_list.html
{% extends 'apps/base/list_base.html' %}
{% block title_table %}
    Lista de negocios
{% endblock %}

{% block content_main_table_data %}
    <tr class="odd" role="row">
        <td class="center text-center">
            {{ obj.id }}
        </td>
        <td class="center text-center">
            {{ obj.nombre }}
        </td>
        <td class="center text-center">
            {{ obj.direccion }}
        </td>
        <td class="center text-center">
            {{ obj.propietario }}
        </td>
        <td class="center text-center">
            {{ obj.tipo_negocio }}
        </td>
        <td class="center text-center">
            <a href="{{ obj.get_update_url }}" class="btn btn-info btn-raised waves-effect btn-xs"
               data-toggle="tooltip" data-placement="top" title=""
               data-original-title="Modificar">
                <i class="fa fa-pencil"></i>
            </a>
        </td>
    </tr>
{% endblock %}

{% block fab %}
<a href="{% url 'emprendimiento:crear_negocio' %}" class="btn btn-primary btn-fab demo-switcher-fab"
        data-toggle="tooltip" data-placement="top"
        title="Crear Negocio">
    <i class="material-icons">add</i>
</a>
{% endblock %}

templates/apps/emprendimiento/oportunidad_comercial_list.html
{% extends 'apps/base/list_base.html' %}
{% block title_table %}
    Lista de Oportunidades Comerciales
{% endblock %}

{% block content_main_table_data %}
    <tr class="odd" role="row">
        <td class="center text-center">
            {{ obj.id }}
        </td>
        <td class="center text-center">
            {{ obj.negocio }}
        </td>
        <td class="center text-center">
            {{ obj.fecha }}
        </td>
        <td class="center text-center">
            {{ obj.empresa }}
        </td>
        <td class="center text-center">
            <a href="{{ obj.get_update_url }}" class="btn btn-info btn-raised waves-effect btn-xs"
               data-toggle="tooltip" data-placement="top" title=""
               data-original-title="Modificar">
                <i class="fa fa-pencil"></i>
            </a>
        </td>
    </tr>
{% endblock %}

{% block fab %}
<a href="{% url 'emprendimiento:crear_oportunidad_comercial' %}" class="btn btn-primary btn-fab demo-switcher-fab"
        data-toggle="tooltip" data-placement="top"
        title="Crear Emprendimiento">
    <i class="material-icons">add</i>
</a>
{% endblock %}

templates/apps/emprendimiento/sector_list.html
{% extends 'apps/base/list_base.html' %}
{% block title_table %}
    Lista de sectores
{% endblock %}

{% block content_main_table_data %}
    <tr class="odd" role="row">
        <td class="center text-center">
            {{ obj.id }}
        </td>
        <td class="center text-center">
            {{ obj.nombre }}
        </td>
        <td class="center text-center">
            <a href="{{ obj.get_update_url }}" class="btn btn-info btn-raised waves-effect btn-xs"
               data-toggle="tooltip" data-placement="top" title=""
               data-original-title="Modificar">
                <i class="fa fa-pencil"></i>
            </a>
        </td>
    </tr>
{% endblock %}

{% block fab %}
<a href="{% url 'emprendimiento:crear_sector' %}" class="btn btn-primary btn-fab demo-switcher-fab"
        data-toggle="tooltip" data-placement="top"
        title="Crear Sector">
    <i class="material-icons">add</i>
</a>
{% endblock %}

templates/apps/emprendimiento/tipo_negocio_list.html
{% extends 'apps/base/list_base.html' %}
{% block title_table %}
    Lista tipos de negocio
{% endblock %}

{% block content_main_table_data %}
    <tr class="odd" role="row">
        <td class="center text-center">
            {{ obj.id }}
        </td>
        <td class="center text-center">
            {{ obj.nombre }}
        </td>
        <td class="center text-center">
            {{ obj.negocios.count }}
        </td>
        <td class="center text-center">
            <a href="{{ obj.get_update_url }}" class="btn btn-info btn-raised waves-effect btn-xs"
               data-toggle="tooltip" data-placement="top" title=""
               data-original-title="Modificar">
                <i class="fa fa-pencil"></i>
            </a>
        </td>
    </tr>
{% endblock %}

{% block fab %}
<a href="{% url 'emprendimiento:crear_tipo_negocio' %}" class="btn btn-primary btn-fab demo-switcher-fab"
        data-toggle="tooltip" data-placement="top"
        title="Crear tipo negocio">
    <i class="material-icons">add</i>
</a>
{% endblock %}

templates/apps/emprendimiento/tipo_unidad_productiva_list.html
{% extends 'apps/base/list_base.html' %}
{% block title_table %}
    Lista tipo Unidad Productiva
{% endblock %}

{% block content_main_table_data %}
    <tr class="odd" role="row">
        <td class="center text-center">
            {{ obj.id }}
        </td>
        <td class="center text-center">
            {{ obj.nombre }}
        </td>
        <td class="center text-center">
            <a href="{{ obj.get_update_url }}" class="btn btn-info btn-raised waves-effect btn-xs"
               data-toggle="tooltip" data-placement="top" title=""
               data-original-title="Modificar">
                <i class="fa fa-pencil"></i>
            </a>
        </td>
    </tr>
{% endblock %}

{% block fab %}
<a href="{% url 'emprendimiento:crear_tipo_unidad_productiva' %}" class="btn btn-primary btn-fab demo-switcher-fab"
        data-toggle="tooltip" data-placement="top"
        title="Crear Tipo Unidad Productiva">
    <i class="material-icons">add</i>
</a>
{% endblock %}